version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydev
    hostname: mydev
    ports:
      - "5679:22"
    volumes:
      - ./home_dev:/home
    networks:
       - monnet
networks:
  monnet:
    driver: bridge
